name: health_api_and_mobile_application
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  mysql1: ^0.20.0
  fl_chart: ^0.62.0


  cupertino_icons: ^1.0.2
  # firebase_core: ^2.13.0
  # flutterfire_cli: ^0.2.7
  http: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/