// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFgaHMGqO_wgKBDOhsAtsghbBGSAztvN4',
    appId: '1:1066715523402:web:0e579ce389e12d7b8ff9b3',
    messagingSenderId: '1066715523402',
    projectId: 'noel-aa7f5',
    authDomain: 'noel-aa7f5.firebaseapp.com',
    databaseURL: 'https://noel-aa7f5-default-rtdb.firebaseio.com',
    storageBucket: 'noel-aa7f5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOGpcE1N075iXKhwxMHdEC-KmExGYgc8Y',
    appId: '1:1066715523402:android:e479ae64564e1ab08ff9b3',
    messagingSenderId: '1066715523402',
    projectId: 'noel-aa7f5',
    databaseURL: 'https://noel-aa7f5-default-rtdb.firebaseio.com',
    storageBucket: 'noel-aa7f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2oC1HGmHkLG1hktqHpx26zu7tgdHLwo8',
    appId: '1:1066715523402:ios:f76a754eff60fe138ff9b3',
    messagingSenderId: '1066715523402',
    projectId: 'noel-aa7f5',
    databaseURL: 'https://noel-aa7f5-default-rtdb.firebaseio.com',
    storageBucket: 'noel-aa7f5.appspot.com',
    iosClientId: '1066715523402-i07d4d187ubqr71q3qcvfflp9q75cumf.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthWorker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2oC1HGmHkLG1hktqHpx26zu7tgdHLwo8',
    appId: '1:1066715523402:ios:f76a754eff60fe138ff9b3',
    messagingSenderId: '1066715523402',
    projectId: 'noel-aa7f5',
    databaseURL: 'https://noel-aa7f5-default-rtdb.firebaseio.com',
    storageBucket: 'noel-aa7f5.appspot.com',
    iosClientId: '1066715523402-i07d4d187ubqr71q3qcvfflp9q75cumf.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthWorker',
  );
}
